# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunchclub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='user',
            field=models.CharField(max_length=200),
        ),
    ]
