# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 03:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lunchclub', '0002_auto_20180104_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrangement',
            name='gastronome',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lunch',
            name='chef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Chef',
        ),
    ]
