# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 01:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lunchclub', '0003_remove_arrangement_chef'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lunchinstance',
            options={'ordering': ['serve_date'], 'permissions': (('can_mark_served', 'Set status as cd'),)},
        ),
    ]
