# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-06 15:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lunchclub', '0003_auto_20180104_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Enter a brief description of the lunch', max_length=1000)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('nutritioncategory', models.ManyToManyField(help_text='Select a nutrition category for this book', to='lunchclub.NutritionCategory')),
            ],
        ),
        migrations.RemoveField(
            model_name='lunchinstance',
            name='lunch',
        ),
        migrations.AlterModelOptions(
            name='lunch',
            options={'ordering': ['serve_date'], 'permissions': (('can_mark_served', 'Set status as cd'),)},
        ),
        migrations.RemoveField(
            model_name='arrangement',
            name='lunchinstance',
        ),
        migrations.RemoveField(
            model_name='lunch',
            name='chef',
        ),
        migrations.RemoveField(
            model_name='lunch',
            name='description',
        ),
        migrations.RemoveField(
            model_name='lunch',
            name='lunchname',
        ),
        migrations.RemoveField(
            model_name='lunch',
            name='nutritioncategory',
        ),
        migrations.AddField(
            model_name='arrangement',
            name='lunch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lunchclub.Lunch'),
        ),
        migrations.AddField(
            model_name='lunch',
            name='information',
            field=models.TextField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lunch',
            name='serve_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lunch',
            name='status',
            field=models.CharField(blank=True, choices=[('po', 'Planned Open'), ('pc', 'Planned Closed'), ('sd', 'Served'), ('cd', 'Cancelled')], default='po', help_text='Status of the Lunch Instance', max_length=2),
        ),
        migrations.AlterField(
            model_name='lunch',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular lunch across all lunches served and planned', primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='LunchInstance',
        ),
        migrations.AddField(
            model_name='lunch',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lunchclub.Recipe'),
        ),
    ]
